//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.1433
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staubli.Robotics.Soap.Proxies.ServerV0
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ServerException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServerException", "CS8ServerV0");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CS8ServerV0", ConfigurationName="Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType")]
    public interface CS8ServerV0PortType
    {
        
        // CODEGEN : Le paramètre « server » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlElementAttribute ».
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="server")]
        Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionResponse getSoapServerVersion(Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionRequest request);
        
        // CODEGEN : Le paramètre « found » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlElementAttribute ».
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="found")]
        Staubli.Robotics.Soap.Proxies.ServerV0.findServerResponse findServer(Staubli.Robotics.Soap.Proxies.ServerV0.findServerRequest request);
        
        // CODEGEN : Le paramètre « message » nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L’attribut spécifique est « System.Xml.Serialization.XmlElementAttribute ».
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.pingResponse ping(Staubli.Robotics.Soap.Proxies.ServerV0.pingRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message getCS8VersionsRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsResponse getCS8Versions(Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message loginResponse contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.loginResponse login(Staubli.Robotics.Soap.Proxies.ServerV0.loginRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message logoutRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.logoutResponse logout(Staubli.Robotics.Soap.Proxies.ServerV0.logoutRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message getRobotsRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsResponse getRobots(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message getRobotJointPosRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosResponse getRobotJointPos(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le message getRobotJntCartPosRequest contient des en-têtes
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosResponse getRobotJntCartPos(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom de wrapper (setRobotPosResponse) du message setRobotJointPosResponse ne correspond pas à la valeur par défaut (setRobotJointPos)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV0.ServerException), Action="", Name="ServerException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosResponse setRobotJointPos(Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public partial class SoapServerVersion
    {
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public partial class CartesianPos
    {
        
        private double xField;
        
        private double yField;
        
        private double zField;
        
        private double rxField;
        
        private double ryField;
        
        private double rzField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double x
        {
            get
            {
                return this.xField;
            }
            set
            {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double z
        {
            get
            {
                return this.zField;
            }
            set
            {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double rx
        {
            get
            {
                return this.rxField;
            }
            set
            {
                this.rxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double ry
        {
            get
            {
                return this.ryField;
            }
            set
            {
                this.ryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double rz
        {
            get
            {
                return this.rzField;
            }
            set
            {
                this.rzField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public partial class Robot
    {
        
        private Kinematic kinematicField;
        
        private string armField;
        
        private string tuningField;
        
        private MountType mountTypeField;
        
        private LengthAxis3 lengthAxis3Field;
        
        private DiameterAxis3 diameterAxis3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Kinematic kinematic
        {
            get
            {
                return this.kinematicField;
            }
            set
            {
                this.kinematicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string arm
        {
            get
            {
                return this.armField;
            }
            set
            {
                this.armField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string tuning
        {
            get
            {
                return this.tuningField;
            }
            set
            {
                this.tuningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public MountType mountType
        {
            get
            {
                return this.mountTypeField;
            }
            set
            {
                this.mountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public LengthAxis3 lengthAxis3
        {
            get
            {
                return this.lengthAxis3Field;
            }
            set
            {
                this.lengthAxis3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public DiameterAxis3 diameterAxis3
        {
            get
            {
                return this.diameterAxis3Field;
            }
            set
            {
                this.diameterAxis3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public enum Kinematic
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KINEMATIC-INVALID")]
        KINEMATICINVALID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KINEMATIC-ANTHROPOMORPH6")]
        KINEMATICANTHROPOMORPH6,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KINEMATIC-ANTHROPOMORPH5")]
        KINEMATICANTHROPOMORPH5,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KINEMATIC-SCARA")]
        KINEMATICSCARA,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("KINEMATIC-EISENMANN")]
        KINEMATICEISENMANN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public enum MountType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MOUNTTYPE-INVALID")]
        MOUNTTYPEINVALID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MOUNTTYPE-FLOOR")]
        MOUNTTYPEFLOOR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MOUNTTYPE-CEILING")]
        MOUNTTYPECEILING,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MOUNTTYPE-WALL")]
        MOUNTTYPEWALL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public enum LengthAxis3
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LENGTHAXIS3-INVALID")]
        LENGTHAXIS3INVALID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LENGTHAXIS3-L100")]
        LENGTHAXIS3L100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LENGTHAXIS3-L200")]
        LENGTHAXIS3L200,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LENGTHAXIS3-L400")]
        LENGTHAXIS3L400,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("LENGTHAXIS3-L600")]
        LENGTHAXIS3L600,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public enum DiameterAxis3
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DIAMETERAXIS3-INVALID")]
        DIAMETERAXIS3INVALID,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DIAMETERAXIS3-D20")]
        DIAMETERAXIS3D20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("DIAMETERAXIS3-D25")]
        DIAMETERAXIS3D25,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="CS8ServerV0")]
    public partial class Version
    {
        
        private string nameField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSoapServerVersion", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getSoapServerVersionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cltName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string cltVersion;
        
        public getSoapServerVersionRequest()
        {
        }
        
        public getSoapServerVersionRequest(string cltName, string cltVersion)
        {
            this.cltName = cltName;
            this.cltVersion = cltVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSoapServerVersionResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getSoapServerVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV0.SoapServerVersion server;
        
        public getSoapServerVersionResponse()
        {
        }
        
        public getSoapServerVersionResponse(Staubli.Robotics.Soap.Proxies.ServerV0.SoapServerVersion server)
        {
            this.server = server;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findServer", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class findServerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serverName;
        
        public findServerRequest()
        {
        }
        
        public findServerRequest(string serverName)
        {
            this.serverName = serverName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findServerResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class findServerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool found;
        
        public findServerResponse()
        {
        }
        
        public findServerResponse(bool found)
        {
            this.found = found;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ping", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class pingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string message;
        
        public pingRequest()
        {
        }
        
        public pingRequest(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pingResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class pingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string message;
        
        public pingResponse()
        {
        }
        
        public pingResponse(string message)
        {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCS8Versions", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getCS8VersionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public getCS8VersionsRequest()
        {
        }
        
        public getCS8VersionsRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCS8VersionsResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getCS8VersionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Versions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Version[] @out;
        
        public getCS8VersionsResponse()
        {
        }
        
        public getCS8VersionsResponse(Version[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="login", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string pwd;
        
        public loginRequest()
        {
        }
        
        public loginRequest(string user, string pwd)
        {
            this.user = user;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loginResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sid;
        
        public loginResponse()
        {
        }
        
        public loginResponse(int sessionId, int sid)
        {
            this.sessionId = sessionId;
            this.sid = sid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logout", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class logoutRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public logoutRequest()
        {
        }
        
        public logoutRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logoutResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class logoutResponse
    {
        
        public logoutResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobots", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public getRobotsRequest()
        {
        }
        
        public getRobotsRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobotsResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Robots", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Robot[] @out;
        
        public getRobotsResponse()
        {
        }
        
        public getRobotsResponse(Robot[] @out)
        {
            this.@out = @out;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobotJointPos", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotJointPosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        public getRobotJointPosRequest()
        {
        }
        
        public getRobotJointPosRequest(int sessionId, int robot)
        {
            this.sessionId = sessionId;
            this.robot = robot;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobotJointPosResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotJointPosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] pos;
        
        public getRobotJointPosResponse()
        {
        }
        
        public getRobotJointPosResponse(double[] pos)
        {
            this.pos = pos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobotJntCartPos", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotJntCartPosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos tool;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos frame;
        
        public getRobotJntCartPosRequest()
        {
        }
        
        public getRobotJntCartPosRequest(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos tool, Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos frame)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.tool = tool;
            this.frame = frame;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRobotJntCartPosResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class getRobotJntCartPosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] jntPos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos cartPos;
        
        public getRobotJntCartPosResponse()
        {
        }
        
        public getRobotJntCartPosResponse(double[] jntPos, Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos cartPos)
        {
            this.jntPos = jntPos;
            this.cartPos = cartPos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRobotJointPos", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class setRobotJointPosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CS8ServerV0", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] pos;
        
        public setRobotJointPosRequest()
        {
        }
        
        public setRobotJointPosRequest(int sessionId, int robot, double[] pos)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.pos = pos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRobotPosResponse", WrapperNamespace="CS8ServerV0", IsWrapped=true)]
    public partial class setRobotJointPosResponse
    {
        
        public setRobotJointPosResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CS8ServerV0PortTypeChannel : Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CS8ServerV0PortTypeClient : System.ServiceModel.ClientBase<Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType>, Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType
    {
        
        public CS8ServerV0PortTypeClient()
        {
        }
        
        public CS8ServerV0PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CS8ServerV0PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CS8ServerV0PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CS8ServerV0PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.getSoapServerVersion(Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionRequest request)
        {
            return base.Channel.getSoapServerVersion(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV0.SoapServerVersion getSoapServerVersion(string cltName, string cltVersion)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionRequest();
            inValue.cltName = cltName;
            inValue.cltVersion = cltVersion;
            Staubli.Robotics.Soap.Proxies.ServerV0.getSoapServerVersionResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).getSoapServerVersion(inValue);
            return retVal.server;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.findServerResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.findServer(Staubli.Robotics.Soap.Proxies.ServerV0.findServerRequest request)
        {
            return base.Channel.findServer(request);
        }
        
        public bool findServer(string serverName)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.findServerRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.findServerRequest();
            inValue.serverName = serverName;
            Staubli.Robotics.Soap.Proxies.ServerV0.findServerResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).findServer(inValue);
            return retVal.found;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.pingResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.ping(Staubli.Robotics.Soap.Proxies.ServerV0.pingRequest request)
        {
            return base.Channel.ping(request);
        }
        
        public void ping(ref string message)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.pingRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.pingRequest();
            inValue.message = message;
            Staubli.Robotics.Soap.Proxies.ServerV0.pingResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).ping(inValue);
            message = retVal.message;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.getCS8Versions(Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsRequest request)
        {
            return base.Channel.getCS8Versions(request);
        }
        
        public Version[] getCS8Versions(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV0.getCS8VersionsResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).getCS8Versions(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.loginResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.login(Staubli.Robotics.Soap.Proxies.ServerV0.loginRequest request)
        {
            return base.Channel.login(request);
        }
        
        public int login(string user, string pwd, out int sid)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.loginRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.loginRequest();
            inValue.user = user;
            inValue.pwd = pwd;
            Staubli.Robotics.Soap.Proxies.ServerV0.loginResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).login(inValue);
            sid = retVal.sid;
            return retVal.sessionId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.logoutResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.logout(Staubli.Robotics.Soap.Proxies.ServerV0.logoutRequest request)
        {
            return base.Channel.logout(request);
        }
        
        public void logout(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.logoutRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.logoutRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV0.logoutResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.getRobots(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsRequest request)
        {
            return base.Channel.getRobots(request);
        }
        
        public Robot[] getRobots(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotsResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).getRobots(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.getRobotJointPos(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosRequest request)
        {
            return base.Channel.getRobotJointPos(request);
        }
        
        public double[] getRobotJointPos(int sessionId, int robot)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJointPosResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).getRobotJointPos(inValue);
            return retVal.pos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.getRobotJntCartPos(Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosRequest request)
        {
            return base.Channel.getRobotJntCartPos(request);
        }
        
        public double[] getRobotJntCartPos(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos tool, Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos frame, out Staubli.Robotics.Soap.Proxies.ServerV0.CartesianPos cartPos)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.tool = tool;
            inValue.frame = frame;
            Staubli.Robotics.Soap.Proxies.ServerV0.getRobotJntCartPosResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).getRobotJntCartPos(inValue);
            cartPos = retVal.cartPos;
            return retVal.jntPos;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosResponse Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType.setRobotJointPos(Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosRequest request)
        {
            return base.Channel.setRobotJointPos(request);
        }
        
        public void setRobotJointPos(int sessionId, int robot, double[] pos)
        {
            Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.pos = pos;
            Staubli.Robotics.Soap.Proxies.ServerV0.setRobotJointPosResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV0.CS8ServerV0PortType)(this)).setRobotJointPos(inValue);
        }
    }
}
