//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staubli.Robotics.Soap.Proxies.ServerV3
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ServerException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServerException", "CS8ServerV0");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:CS8ServerV3", ConfigurationName="Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType")]
    public interface CS8ServerV3PortType
    {
        
        // CODEGEN: Generating message contract since message forwardKinRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinResponse forwardKin(Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinRequest request);
        
        // CODEGEN: Generating message contract since message reverseKinRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinResponse reverseKin(Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (moveResponse) of message moveJJResponse does not match the default value (moveJJ)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse moveJJ(Staubli.Robotics.Soap.Proxies.ServerV3.moveJJRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (moveResponse) of message moveJCResponse does not match the default value (moveJC)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse moveJC(Staubli.Robotics.Soap.Proxies.ServerV3.moveJCRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (moveResponse) of message moveLResponse does not match the default value (moveL)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse moveL(Staubli.Robotics.Soap.Proxies.ServerV3.moveLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (moveResponse) of message moveCResponse does not match the default value (moveC)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse moveC(Staubli.Robotics.Soap.Proxies.ServerV3.moveCRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (motionResponse) of message resetMotionResponse does not match the default value (resetMotion)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse resetMotion(Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (motionResponse) of message stopMotionResponse does not match the default value (stopMotion)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse stopMotion(Staubli.Robotics.Soap.Proxies.ServerV3.stopMotionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (motionResponse) of message restartMotionResponse does not match the default value (restartMotion)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse restartMotion(Staubli.Robotics.Soap.Proxies.ServerV3.restartMotionRequest request);
        
        // CODEGEN: Generating message contract since message setSchedulingModeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeResponse setSchedulingMode(Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (MotionAndRobotsPos) of message schedulerRefreshResponse does not match the default value (schedulerRefresh)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshResponse schedulerRefresh(Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshRequest request);
        
        // CODEGEN: Generating message contract since message setPowerRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Staubli.Robotics.Soap.Proxies.ServerV3.ServerException), Action="", Name="ServerException", Namespace="CS8ServerV0")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        Staubli.Robotics.Soap.Proxies.ServerV3.setPowerResponse setPower(Staubli.Robotics.Soap.Proxies.ServerV3.setPowerRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class Frame
    {
        
        private double nxField;
        
        private double nyField;
        
        private double nzField;
        
        private double oxField;
        
        private double oyField;
        
        private double ozField;
        
        private double axField;
        
        private double ayField;
        
        private double azField;
        
        private double pxField;
        
        private double pyField;
        
        private double pzField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double nx
        {
            get
            {
                return this.nxField;
            }
            set
            {
                this.nxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ny
        {
            get
            {
                return this.nyField;
            }
            set
            {
                this.nyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double nz
        {
            get
            {
                return this.nzField;
            }
            set
            {
                this.nzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double ox
        {
            get
            {
                return this.oxField;
            }
            set
            {
                this.oxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double oy
        {
            get
            {
                return this.oyField;
            }
            set
            {
                this.oyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double oz
        {
            get
            {
                return this.ozField;
            }
            set
            {
                this.ozField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double ax
        {
            get
            {
                return this.axField;
            }
            set
            {
                this.axField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double ay
        {
            get
            {
                return this.ayField;
            }
            set
            {
                this.ayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double az
        {
            get
            {
                return this.azField;
            }
            set
            {
                this.azField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double px
        {
            get
            {
                return this.pxField;
            }
            set
            {
                this.pxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double py
        {
            get
            {
                return this.pyField;
            }
            set
            {
                this.pyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double pz
        {
            get
            {
                return this.pzField;
            }
            set
            {
                this.pzField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class RobotPos
    {
        
        private bool settledField;
        
        private double[] jointField;
        
        private Frame positionField;
        
        private Config configField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool settled
        {
            get
            {
                return this.settledField;
            }
            set
            {
                this.settledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] joint
        {
            get
            {
                return this.jointField;
            }
            set
            {
                this.jointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Frame position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Config config
        {
            get
            {
                return this.configField;
            }
            set
            {
                this.configField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class Config
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("anthroConfig", typeof(AnthroConfig), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("scaraConfig", typeof(ScaraConfig), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("vrbxConfig", typeof(VrbxConfig), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class AnthroConfig
    {
        
        private ShoulderConfig shoulderField;
        
        private PositiveNegativeConfig elbowField;
        
        private PositiveNegativeConfig wristField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ShoulderConfig shoulder
        {
            get
            {
                return this.shoulderField;
            }
            set
            {
                this.shoulderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PositiveNegativeConfig elbow
        {
            get
            {
                return this.elbowField;
            }
            set
            {
                this.elbowField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PositiveNegativeConfig wrist
        {
            get
            {
                return this.wristField;
            }
            set
            {
                this.wristField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum ShoulderConfig
    {
        
        /// <remarks/>
        SSAME,
        
        /// <remarks/>
        LEFTY,
        
        /// <remarks/>
        RIGHTY,
        
        /// <remarks/>
        SFREE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum PositiveNegativeConfig
    {
        
        /// <remarks/>
        PNSAME,
        
        /// <remarks/>
        POSITIVE,
        
        /// <remarks/>
        NEGATIVE,
        
        /// <remarks/>
        PNFREE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class ScaraConfig
    {
        
        private ShoulderConfig shoulderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ShoulderConfig shoulder
        {
            get
            {
                return this.shoulderField;
            }
            set
            {
                this.shoulderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class VrbxConfig
    {
        
        private AboveBelowConfig jnt1Field;
        
        private PositiveNegativeConfig jnt3Field;
        
        private PositiveNegativeConfig jnt5Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public AboveBelowConfig jnt1
        {
            get
            {
                return this.jnt1Field;
            }
            set
            {
                this.jnt1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public PositiveNegativeConfig jnt3
        {
            get
            {
                return this.jnt3Field;
            }
            set
            {
                this.jnt3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public PositiveNegativeConfig jnt5
        {
            get
            {
                return this.jnt5Field;
            }
            set
            {
                this.jnt5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum AboveBelowConfig
    {
        
        /// <remarks/>
        ABSAME,
        
        /// <remarks/>
        ABOVE,
        
        /// <remarks/>
        BELOW,
        
        /// <remarks/>
        ABFREE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public partial class MotionDesc
    {
        
        private Frame toolField;
        
        private Frame frameField;
        
        private MoveType absRelField;
        
        private Config configField;
        
        private BlendType blendTypeField;
        
        private double distBlendPrevField;
        
        private double distBlendNextField;
        
        private double velField;
        
        private double accField;
        
        private double decField;
        
        private double transVelField;
        
        private double rotVelField;
        
        private double freqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Frame tool
        {
            get
            {
                return this.toolField;
            }
            set
            {
                this.toolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Frame frame
        {
            get
            {
                return this.frameField;
            }
            set
            {
                this.frameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MoveType absRel
        {
            get
            {
                return this.absRelField;
            }
            set
            {
                this.absRelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Config config
        {
            get
            {
                return this.configField;
            }
            set
            {
                this.configField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public BlendType blendType
        {
            get
            {
                return this.blendTypeField;
            }
            set
            {
                this.blendTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double distBlendPrev
        {
            get
            {
                return this.distBlendPrevField;
            }
            set
            {
                this.distBlendPrevField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double distBlendNext
        {
            get
            {
                return this.distBlendNextField;
            }
            set
            {
                this.distBlendNextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double vel
        {
            get
            {
                return this.velField;
            }
            set
            {
                this.velField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double acc
        {
            get
            {
                return this.accField;
            }
            set
            {
                this.accField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double dec
        {
            get
            {
                return this.decField;
            }
            set
            {
                this.decField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public double transVel
        {
            get
            {
                return this.transVelField;
            }
            set
            {
                this.transVelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double rotVel
        {
            get
            {
                return this.rotVelField;
            }
            set
            {
                this.rotVelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double freq
        {
            get
            {
                return this.freqField;
            }
            set
            {
                this.freqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum MoveType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("ABSOLUTE-MOVE")]
        ABSOLUTEMOVE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("RELATIVE-MOVE")]
        RELATIVEMOVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum BlendType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BLEND-OFF")]
        BLENDOFF,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BLEND-JOINT")]
        BLENDJOINT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("BLEND-CART")]
        BLENDCART,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV1")]
    public partial class JointRange
    {
        
        private double[] minField;
        
        private double[] maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double[] min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double[] max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="forwardKin", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class forwardKinRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] joint;
        
        public forwardKinRequest()
        {
        }
        
        public forwardKinRequest(int sessionId, int robot, double[] joint)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.joint = joint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="forwardKinResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class forwardKinResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "urn:CS8ServerV3", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame position;
        
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Config config;
        
        public forwardKinResponse()
        {
        }
        
        //.................original code:.......................ServerV3.Frame position
        public forwardKinResponse(Staubli.Robotics.Soap.Proxies.ServerV3.Frame position, Staubli.Robotics.Soap.Proxies.ServerV3.Config config)
        {
            this.position = position;
            this.config = config;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum ReversingResult
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("REVERSE-OK")]
        REVERSEOK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("NO-CONVERGENCE")]
        NOCONVERGENCE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OUT-OF-JNT-RANGE")]
        OUTOFJNTRANGE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("OUT-OF-WORKSPACE")]
        OUTOFWORKSPACE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INVALID-CONFIG")]
        INVALIDCONFIG,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INVALID-ORIENTATION")]
        INVALIDORIENTATION,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UNSUPPORTED-KINEMATICS")]
        UNSUPPORTEDKINEMATICS,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("UNCONSTRAINT-FRAME")]
        UNCONSTRAINTFRAME,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("INVALID-ERROR-CODE")]
        INVALIDERRORCODE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reverseKin", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class reverseKinRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] jointIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame target;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Config config;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.JointRange jointRange;
        
        public reverseKinRequest()
        {
        }
        
        public reverseKinRequest(int sessionId, int robot, double[] jointIn, Staubli.Robotics.Soap.Proxies.ServerV3.Frame target, Staubli.Robotics.Soap.Proxies.ServerV3.Config config, Staubli.Robotics.Soap.Proxies.ServerV3.JointRange jointRange)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.jointIn = jointIn;
            this.target = target;
            this.config = config;
            this.jointRange = jointRange;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reverseKinResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class reverseKinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] jointOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.ReversingResult reversingResult;
        
        public reverseKinResponse()
        {
        }
        
        public reverseKinResponse(double[] jointOut, Staubli.Robotics.Soap.Proxies.ServerV3.ReversingResult reversingResult)
        {
            this.jointOut = jointOut;
            this.reversingResult = reversingResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum MotionReturnCode
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCSV3-MOT-NO-ERR")]
        SCSV3MOTNOERR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCSV3-MOT-NOT-READY")]
        SCSV3MOTNOTREADY,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCSV3-MOT-ERR-PARAM")]
        SCSV3MOTERRPARAM,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCSV3-MOT-ERR-MISUSE")]
        SCSV3MOTERRMISUSE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCSV3-MOT-ERR-UNEXPECTED")]
        SCSV3MOTERRUNEXPECTED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveJJ", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class moveJJRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public double[] joint;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc;
        
        public moveJJRequest()
        {
        }
        
        public moveJJRequest(int sessionId, int robot, double[] joint, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.joint = joint;
            this.mdesc = mdesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class moveJJResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet;
        
        public moveJJResponse()
        {
        }
        
        public moveJJResponse(int id, Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            this.id = id;
            this.motRet = motRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveJC", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class moveJCRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc;
        
        public moveJCRequest()
        {
        }
        
        public moveJCRequest(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.frame = frame;
            this.mdesc = mdesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveL", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class moveLRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc;
        
        public moveLRequest()
        {
        }
        
        public moveLRequest(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.frame = frame;
            this.mdesc = mdesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveC", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class moveCRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int robot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameB;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc;
        
        public moveCRequest()
        {
        }
        
        public moveCRequest(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameB, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameC, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc)
        {
            this.sessionId = sessionId;
            this.robot = robot;
            this.frameB = frameB;
            this.frameC = frameC;
            this.mdesc = mdesc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="resetMotion", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class resetMotionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public resetMotionRequest()
        {
        }
        
        public resetMotionRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="motionResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class resetMotionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet;
        
        public resetMotionResponse()
        {
        }
        
        public resetMotionResponse(Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            this.motRet = motRet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="stopMotion", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class stopMotionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public stopMotionRequest()
        {
        }
        
        public stopMotionRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="restartMotion", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class restartMotionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public restartMotionRequest()
        {
        }
        
        public restartMotionRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum SchedulingMode
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCHEDULING-INTERNAL")]
        SCHEDULINGINTERNAL,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("SCHEDULING-EXTERNAL")]
        SCHEDULINGEXTERNAL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSchedulingMode", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class setSchedulingModeRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulingMode;
        
        public setSchedulingModeRequest()
        {
        }
        
        public setSchedulingModeRequest(int sessionId, Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulingMode)
        {
            this.sessionId = sessionId;
            this.schedulingMode = schedulingMode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSchedulingModeResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class setSchedulingModeResponse
    {
        
        public setSchedulingModeResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="schedulerRefresh", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class schedulerRefreshRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        public schedulerRefreshRequest()
        {
        }
        
        public schedulerRefreshRequest(int sessionId)
        {
            this.sessionId = sessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="MotionAndRobotsPos", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class schedulerRefreshResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulingMode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool motionEmpty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("RobotsPos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RobotPos[] allRobotsPos;
        
        public schedulerRefreshResponse()
        {
        }
        
        public schedulerRefreshResponse(Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulingMode, bool motionEmpty, RobotPos[] allRobotsPos)
        {
            this.schedulingMode = schedulingMode;
            this.motionEmpty = motionEmpty;
            this.allRobotsPos = allRobotsPos;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.648")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:CS8ServerV3")]
    public enum PowerReturnCode
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWER-NO-ERR")]
        POWERNOERR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWER-CHANGE-WHILE-ROBOT-NOT-STOPPED")]
        POWERCHANGEWHILEROBOTNOTSTOPPED,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWER-ENABLE-TIMEOUT")]
        POWERENABLETIMEOUT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWER-DISABLE-TIMEOUT")]
        POWERDISABLETIMEOUT,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("POWER-CHANGE-ONLY-IN-REMOTE-MODE")]
        POWERCHANGEONLYINREMOTEMODE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPower", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class setPowerRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="CS8ServerV0")]
        public int sessionId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool power;
        
        public setPowerRequest()
        {
        }
        
        public setPowerRequest(int sessionId, bool power)
        {
            this.sessionId = sessionId;
            this.power = power;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setPowerResponse", WrapperNamespace="urn:CS8ServerV3", IsWrapped=true)]
    public partial class setPowerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:CS8ServerV3", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Staubli.Robotics.Soap.Proxies.ServerV3.PowerReturnCode code;
        
        public setPowerResponse()
        {
        }
        
        public setPowerResponse(Staubli.Robotics.Soap.Proxies.ServerV3.PowerReturnCode code)
        {
            this.code = code;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CS8ServerV3PortTypeChannel : Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CS8ServerV3PortTypeClient : System.ServiceModel.ClientBase<Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType>, Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType
    {
        
        public CS8ServerV3PortTypeClient()
        {
        }
        
        public CS8ServerV3PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public CS8ServerV3PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CS8ServerV3PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public CS8ServerV3PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.forwardKin(Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinRequest request)
        {
            return base.Channel.forwardKin(request);
        }
        //...................original code.........V3.Frame forwardKin
        public Staubli.Robotics.Soap.Proxies.ServerV3.Frame forwardKin(int sessionId, int robot, double[] joint, out Staubli.Robotics.Soap.Proxies.ServerV3.Config config)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.joint = joint;
            Staubli.Robotics.Soap.Proxies.ServerV3.forwardKinResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).forwardKin(inValue);
            config = retVal.config;
            return retVal.position;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.reverseKin(Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinRequest request)
        {
            return base.Channel.reverseKin(request);
        }
        
        public double[] reverseKin(int sessionId, int robot, double[] jointIn, Staubli.Robotics.Soap.Proxies.ServerV3.Frame target, Staubli.Robotics.Soap.Proxies.ServerV3.Config config, Staubli.Robotics.Soap.Proxies.ServerV3.JointRange jointRange, out Staubli.Robotics.Soap.Proxies.ServerV3.ReversingResult reversingResult)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.jointIn = jointIn;
            inValue.target = target;
            inValue.config = config;
            inValue.jointRange = jointRange;
            Staubli.Robotics.Soap.Proxies.ServerV3.reverseKinResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).reverseKin(inValue);
            reversingResult = retVal.reversingResult;
            return retVal.jointOut;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.moveJJ(Staubli.Robotics.Soap.Proxies.ServerV3.moveJJRequest request)
        {
            return base.Channel.moveJJ(request);
        }
        
        public int moveJJ(int sessionId, int robot, double[] joint, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc, out Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJJRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.moveJJRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.joint = joint;
            inValue.mdesc = mdesc;
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).moveJJ(inValue);
            motRet = retVal.motRet;
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.moveJC(Staubli.Robotics.Soap.Proxies.ServerV3.moveJCRequest request)
        {
            return base.Channel.moveJC(request);
        }
        
        public int moveJC(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc, out Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJCRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.moveJCRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.frame = frame;
            inValue.mdesc = mdesc;
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).moveJC(inValue);
            motRet = retVal.motRet;
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.moveL(Staubli.Robotics.Soap.Proxies.ServerV3.moveLRequest request)
        {
            return base.Channel.moveL(request);
        }
        
        public int moveL(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frame, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc, out Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.moveLRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.moveLRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.frame = frame;
            inValue.mdesc = mdesc;
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).moveL(inValue);
            motRet = retVal.motRet;
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.moveC(Staubli.Robotics.Soap.Proxies.ServerV3.moveCRequest request)
        {
            return base.Channel.moveC(request);
        }
        
        public int moveC(int sessionId, int robot, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameB, Staubli.Robotics.Soap.Proxies.ServerV3.Frame frameC, Staubli.Robotics.Soap.Proxies.ServerV3.MotionDesc mdesc, out Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode motRet)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.moveCRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.moveCRequest();
            inValue.sessionId = sessionId;
            inValue.robot = robot;
            inValue.frameB = frameB;
            inValue.frameC = frameC;
            inValue.mdesc = mdesc;
            Staubli.Robotics.Soap.Proxies.ServerV3.moveJJResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).moveC(inValue);
            motRet = retVal.motRet;
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.resetMotion(Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionRequest request)
        {
            return base.Channel.resetMotion(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode resetMotion(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).resetMotion(inValue);
            return retVal.motRet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.stopMotion(Staubli.Robotics.Soap.Proxies.ServerV3.stopMotionRequest request)
        {
            return base.Channel.stopMotion(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode stopMotion(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.stopMotionRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.stopMotionRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).stopMotion(inValue);
            return retVal.motRet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.restartMotion(Staubli.Robotics.Soap.Proxies.ServerV3.restartMotionRequest request)
        {
            return base.Channel.restartMotion(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV3.MotionReturnCode restartMotion(int sessionId)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.restartMotionRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.restartMotionRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV3.resetMotionResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).restartMotion(inValue);
            return retVal.motRet;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.setSchedulingMode(Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeRequest request)
        {
            return base.Channel.setSchedulingMode(request);
        }
        
        public void setSchedulingMode(int sessionId, Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulingMode)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeRequest();
            inValue.sessionId = sessionId;
            inValue.schedulingMode = schedulingMode;
            Staubli.Robotics.Soap.Proxies.ServerV3.setSchedulingModeResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).setSchedulingMode(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.schedulerRefresh(Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshRequest request)
        {
            return base.Channel.schedulerRefresh(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV3.SchedulingMode schedulerRefresh(int sessionId, out bool motionEmpty, out RobotPos[] allRobotsPos)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshRequest();
            inValue.sessionId = sessionId;
            Staubli.Robotics.Soap.Proxies.ServerV3.schedulerRefreshResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).schedulerRefresh(inValue);
            motionEmpty = retVal.motionEmpty;
            allRobotsPos = retVal.allRobotsPos;
            return retVal.schedulingMode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Staubli.Robotics.Soap.Proxies.ServerV3.setPowerResponse Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType.setPower(Staubli.Robotics.Soap.Proxies.ServerV3.setPowerRequest request)
        {
            return base.Channel.setPower(request);
        }
        
        public Staubli.Robotics.Soap.Proxies.ServerV3.PowerReturnCode setPower(int sessionId, bool power)
        {
            Staubli.Robotics.Soap.Proxies.ServerV3.setPowerRequest inValue = new Staubli.Robotics.Soap.Proxies.ServerV3.setPowerRequest();
            inValue.sessionId = sessionId;
            inValue.power = power;
            Staubli.Robotics.Soap.Proxies.ServerV3.setPowerResponse retVal = ((Staubli.Robotics.Soap.Proxies.ServerV3.CS8ServerV3PortType)(this)).setPower(inValue);
            return retVal.code;
        }
    }
}
